
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
  namespace: default
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 3000
  selector:
    name: go-web-app


---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-ingress
  namespace: default
spec:
  rules:
  - host: go-web-app.192-168-1-25.sslip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-web-service
            port:
              number: 80